services:
  db-mysql:
    image: mysql:8.0
    container_name: mysql-container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3310:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - spring-mysql

  spring-boot:
    container_name: my-java-app
#    build:
#      context: .
    image: ${IMAGE_SPRINGBOOT_CICD}
    ports:
      - 8089:8080
    environment:
      SPRING_DATASOURCE_URL: ${DB_URL:-url}
      SPRING_DATASOURCE_USERNAME: ${DB_USERNAME:-username}
      SPRING_DATASOURCE_PASSWORD: ${DB_PASSWORD:-password}
    networks:
      - spring-mysql

volumes:
  mysql-data:

networks:
  spring-mysql: