server.port=8080
#
# JDBC properties
#
spring.datasource.url=${DATASOURCE_URL:jdbc:postgresql://localhost:5432/employee_directory}
spring.datasource.username=${DATASOURCE_USERNAME:username}
spring.datasource.password=${DATASOURCE_PASSWORD:password}
spring.jpa.hibernate.ddl-auto=update