name: Spring Boot CI CD AWS

on:
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      # Step 1: Send notification
      - name: slack - GitHub Actions Slack integration
        uses: act10ns/slack@v2.1.0
        with:
          status: In progress
          channel: '#workflows'
        if: always() # To ensure the Slack message is sent even if the job fails

      # Step 2: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 3: Set up Java (adjust the version based on your project)
      - name: Set up JDK
        id: setup_jdk
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 4: Cache Maven dependencies (optional for faster builds)
      - name: Cache Maven Dependencies
        id: cache_maven_dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-
            maven-

      # Step 5: Run Unit Tests
      - name: Run tests
        id: run_testing
        run: mvn test

      # Step 6: Build the JAR file
      - name: Build JAR file
        id: build_jar
        run: mvn clean package

      # Step 7: Login to Docker Hub
      - name: Login to Docker Hub
        id: login_dockerhub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      # Step 8: Get short commit hash
      - name: Get short commit hash
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV # This appends the following line to the $GITHUB_ENV file

      # Step 9: Build the Docker image
      - name: Build Docker Image
        id: build_docker_image
        run: |
         docker build -t ${{ secrets.DOCKER_USERNAME }}/springbootcicdaws:${{ env.SHORT_SHA }} .
         docker tag ${{ secrets.DOCKER_USERNAME }}/springbootcicdaws:${{ env.SHORT_SHA }} ${{ secrets.DOCKER_USERNAME }}/springbootcicdaws:latest

      # Step 10: Push the Docker image to Docker Hub
      - name: Push Docker Image
        id: push_docker_image
        run: |
         docker push ${{ secrets.DOCKER_USERNAME }}/springbootcicdaws:${{ env.SHORT_SHA }}
         docker push ${{ secrets.DOCKER_USERNAME }}/springbootcicdaws:latest

      # Step 11: Send completed notification
      - name: slack - GitHub Actions Slack integration
        uses: act10ns/slack@v2.1.0
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#workflows'
        if: always()

  deploy:
    needs: build_and_test # the deploy job will wait until the build_and_test job is completed successfully.
    runs-on: [springboot-aws-ec2]

    steps:
      # Step 1: Send notification
      - name: slack - GitHub Actions Slack integration
        uses: act10ns/slack@v2.1.0
        with:
          status: In progress
          channel: '#workflows'
        if: always() # To ensure the Slack message is sent even if the job fails

      # Step 1: Stop docker compose
      - name: Stop docker compose
        id: stop_docker_compose
        run: docker compose down

      # Step 2: Remove old docker image
      - name: Remove old Docker image
        id: remove_old_image
        run: |
          IMAGE_ID=$(docker images -q mirfanduri/springbootcicdaws:latest)
          if [ -n "$IMAGE_ID" ]; then
            echo "Removing old image: $IMAGE_ID"
            docker rmi $IMAGE_ID || true  # 'true' to ignore error if image doesn't exist
          fi

      # Step 3: Pull image from Docker Hub
      - name: Pull image from Docker Hub
        id: pull_docker_image
        run: docker pull mirfanduri/springbootcicdaws:latest

      # Step 4: Run docker compose using environment file
      - name: Run docker compose
        id: run_docker_compose
        run: docker compose --env-file .env up -d

      # Step 11: Send completed notification
      - name: slack - GitHub Actions Slack integration
        uses: act10ns/slack@v2.1.0
        with:
          status: ${{ job.status }}
          steps: ${{ toJson(steps) }}
          channel: '#workflows'
        if: always()
