name: Spring Boot CI CD AWS

on:
  pull_request:
    branches:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    env:
      SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

    steps:
      # Step 1: Send starting notification
      - name: Start building docker image and push to docker hub
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook-type: webhook-trigger
          payload: |
            {
              "blocks": [
                  {
                    "type": "context",
                    "elements": [
                      {
                        "type": "image",
                        "image_url": "https://avatars.githubusercontent.com/u/36037747?s=400&u=2222e4157a629a700676c524dd5ae1e3b2e0ef02&v=4",
                        "alt_text": "picture of a person"
                      },
                      {
                        "type": "mrkdwn",
                        "text": "*${{ github.repository_owner }}*."
                      }
                    ]
                  },
                  {
                    "type": "divider"
                  }
              ]
            },
            {
                "type": "divider"
            },
            {
                "type": "context",
                "elements": [
                    {
                        "type": "plain_text",
                        "text": "Triggered via ${{ github.action }}",
                        "emoji": true
                    }
                ]
            }
        if: always() # To ensure the Slack message is sent even if the job fails

      # Step 2: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 3: Set up Java (adjust the version based on your project)
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Step 4: Cache Maven dependencies (optional for faster builds)
      - name: Cache Maven Dependencies
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: maven-${{ runner.os }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ runner.os }}-

      # Step 5: Run Unit Tests
      - name: Run tests
        run: mvn test

      # Step 6: Build the JAR file
      - name: Build JAR file
        run: mvn clean package

      # Step 7: Login to Docker Hub
      - name: Login to Docker Hub
        run: docker login -u ${{secrets.DOCKER_USERNAME}} -p ${{secrets.DOCKER_PASSWORD}}

      # Step 8: Get short commit hash
      - name: Get short commit hash
        run: echo "SHORT_SHA=${GITHUB_SHA::7}" >> $GITHUB_ENV # This appends the following line to the $GITHUB_ENV file

      # Step 9: Build the Docker image
      - name: Build Docker Image
        run: |
         docker build -t ${{ secrets.DOCKER_USERNAME }}/springbootcicdaws:${{ env.SHORT_SHA }} .
         docker tag ${{ secrets.DOCKER_USERNAME }}/springbootcicdaws:${{ env.SHORT_SHA }} ${{ secrets.DOCKER_USERNAME }}/springbootcicdaws:latest

      # Step 10: Push the Docker image to Docker Hub
      - name: Push Docker Image
        run: |
         docker push ${{ secrets.DOCKER_USERNAME }}/springbootcicdaws:${{ env.SHORT_SHA }}
         docker push ${{ secrets.DOCKER_USERNAME }}/springbootcicdaws:latest

      # Step 11: Send completed notification


#  deploy:
#    needs: build_and_test # the deploy job will wait until the build_and_test job is completed successfully.
#    runs-on: [springboot-aws-ec2]
#
#    steps:
#      # Step 1: Stop docker compose
#      - name: Stop docker compose
#        run: docker compose down
#
#      # Step 2: Remove old docker image
#      - name: Remove old Docker image
#        run: |
#          IMAGE_ID=$(docker images -q mirfanduri/springbootcicdaws:latest)
#          if [ -n "$IMAGE_ID" ]; then
#            echo "Removing old image: $IMAGE_ID"
#            docker rmi $IMAGE_ID || true  # 'true' to ignore error if image doesn't exist
#          fi
#
#      # Step 3: Pull image from Docker Hub
#      - name: Pull image from Docker Hub
#        run: docker pull mirfanduri/springbootcicdaws:latest
#
#      # Step 4: Run docker compose using environment file
#      - name: Run docker compose
#        run: docker compose --env-file .env up -d
